### ISSUE TITLE
Kompilierte APK?

### ISSUE THREAD

**Issue by MasterYiDerSchlitzerOfDoom** [moritzf/vertretungsplan-itg-android#12]
Hallo
könntet ihr bitte eine kompilierte APK auch hochladen. Ich würde eure App gern benutzen aber die Datein runterzuladen, in Eclipse importieren um dort die .apk zu erstellen ist ein bisschen aufwendig. 
Wäre super wenn ihr die mit hochladen könntet.

**Comment by moritzf** [comment]
Hallo MasterYiDerSchlitzerOfDoom,

falls du unsere App ausprobieren möchtest, kannst du sie unter folgendem Link herunterladen: 

https://slack-files.com/T03RLM46X-F0CP8R8BU-e2d3a517d4

Viel Spaß!
